site_name: Robo
theme: mkdocs
site_favicon: img/favicon.png
theme_dir: robotheme
site_url: http://robo.li
repo_url: https://github.com/codegyre/robo/
pages:
- ['index.md', 'Introduction']
- [started.md, Getting Started]
- [tasks/Base.md, Tasks, Base Tasks]
- [tasks/FileSystem.md, Tasks, FileSystem Tasks]
- [tasks/File.md, Tasks, File Tasks]
- [tasks/Composer.md, Tasks, Composer Tasks]
- [tasks/Vcs.md, Tasks, VCS Tasks]
- [tasks/Development.md, Tasks, Development Tasks]
- [tasks/Assets.md, Tasks, Assets Tasks]
- [tasks/Remote.md, Tasks, 'SSH, Rsync Tasks']
- [tasks/Testing.md, Tasks, Testing Tasks]
- [tasks/Npm.md, Tasks, NPM Tasks]
- [tasks/Bower.md, Tasks, Bower Tasks]
- [tasks/Gulp.md, Tasks, Gulp Tasks]
- [tasks/Docker.md, Tasks, Docker Tasks]
- [tasks/ApiGen.md, Tasks, ApiGen Tasks]
- [changelog.md, 'Releases']
extra_css:
- /css/robo.css